apiVersion: v1
kind: Namespace
metadata:
  name: jenkins-ci
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
  namespace: jenkins-ci
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: registry.cn-hangzhou.aliyuncs.com/showerlee/jenkins:2.60.3
          ports:
            - containerPort: 8080
            - containerPort: 50000
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
      volumes:
        - name: jenkins-home
          emptyDir: {}
      nodeSelector:
        system: ci
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: jenkins-ci
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32000
  selector:
    app: jenkins
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-jnlp
  namespace: jenkins-ci
spec:
  type: NodePort
  ports:
    - port: 50000
      targetPort: 50000
      nodePort: 32001
  selector:
    app: jenkins
